# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_auto_20160702_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 10, 55, 37, 65469, tzinfo=utc)),
        ),
    ]
